name: ci
on: [pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
          # golangci-lint command line arguments.
          args: --max-issues-per-linter=0 --max-same-issues=0 --modules-download-mode=vendor
